name: flutter_app_tv
description: TvFlix

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0+3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.2.3
  carousel_slider: ^4.0.0
  flutter_rating_bar: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  video_player: ^2.1.6
  http: ^0.13.4
  better_player: ^0.0.81
  url_launcher: ^6.0.6
  font_awesome_flutter: ^9.2.0
  cached_network_image: ^3.2.0
  animated_text_kit: ^4.2.1
  flutter_html: ^2.2.1
  shared_preferences: ^2.0.13
  firebase_core: ^1.12.0
  google_sign_in: ^5.2.4
  firebase_auth: ^3.3.7
  flutter_facebook_auth: ^4.1.1
  fluttertoast: ^8.0.8
  need_resume: ^1.0.6
  flutter_launcher_icons: "^0.9.2"
  wakelock: ^0.5.6
  flutter_math_fork: ^0.5.0
  provider: ^6.0.0
  transparent_image: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  change_app_package_name: ^1.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Oduda
      fonts:
        - asset: assets/fonts/Oduda.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
